---
- name: Configure SCCM Discovery Methods
  synzack.ludus_sccm.discovery_methods:
    site_code: '{{ ludus_sccm_sitecode }}'
    enable_forest_discovery: '{{ ludus_sccm_enable_active_directory_forest_discovery }}'
    enable_ad_boundary_creation: '{{ ludus_sccm_enable_active_directory_boundary_creation }}'
    enable_subnet_boundary_creation: '{{ ludus_sccm_enable_subnet_boundary_creation }}'
    enable_active_directory_group_discovery: '{{ ludus_sccm_enable_active_directory_group_discovery }}'
    enable_active_directory_system_discovery: '{{ ludus_sccm_enable_active_directory_system_discovery }}'
    enable_active_directory_user_discovery: '{{ ludus_sccm_enable_active_directory_user_discovery }}'
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  register: result
  until: result is succeeded
  retries: 5
  delay: 60
  failed_when: result is failed

# Configure Boundary Group
- name: Configure Boundary Group
  synzack.ludus_sccm.create_boundary_group:
    site_code: '{{ ludus_sccm_sitecode }}'
    boundary_group_name: "Discovery Default Boundary Group"
    boundary_group_description: "Default Ludus Boundary Group"
    site_system_server_names:
      - '{{ ludus_sccm_site_server_hostname }}.{{ ludus_domain_fqdn }}'
      - '{{ ludus_sccm_distro_server_hostname }}.{{ ludus_domain_fqdn }}'
      - '{{ ludus_sccm_mgmt_server_hostname }}.{{ ludus_domain_fqdn }}'
      - '{{ ludus_sccm_sql_server_hostname }}.{{ ludus_domain_fqdn }}'
    boundary: '{{ ludus_domain_fqdn }}/Default-First-Site-Name'
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ ludus_domain_fqdn }}\{{ defaults.ad_domain_admin }}'
    ansible_become_password: '{{ defaults.ad_domain_admin_password }}'
    ansible_become_flags: "logon_type=interactive logon_flags=with_profile"
  when: ludus_sccm_enable_active_directory_boundary_creation
  register: result
  until: result is succeeded
  retries: 5
  delay: 60
  failed_when: result is failed